#!/usr/bin/env python

import sys
import os

dir = os.path.dirname(os.path.realpath(__file__))

if os.environ.get("PYTHONPATH") is None:
    os.environ["PYTHONPATH"] = dir
else:
    os.environ["PYTHONPATH"] = os.pathsep.join(
        [
            dir,
            os.environ.get("PYTHONPATH"),
        ]
    )

os.execl(sys.executable, sys.executable, "-m", "dada_cli", *sys.argv[1:])
